---
title: "Introduction"
author: "Paul Hegedus"
output: html_document
---
The prominence of agriculture in the climate crisis is only beginning. Agricultural land occupies 37.5% of the total land area on the Earth (World Bank 2016), the highest of any type of land use, and contributes between 10 - 25% of all greenhouse gas emissions in 2017 (Farm Bureau 2019, Smith et al. 2014). With the global population increasing and the amount of land available to cultivate decreasing, farmers and ranchers will be faced with the dilemma of feeding more people without increasing the acreage on which to grow crops, while the land on which we currently grow crops is degraded by modern farm practices (FAO 2003). 

As the tenants of these systems, farmers and ranchers will determine the way in which a third of the total land area on earth is managed. However, despite the vast amount of land controlled by farmers, only 5% of the population in developed nations work agriculture related jobs (Roser 2020). Despite the amount of cultivated land not decreasing, there were 6.5 million farms in the USA in the 1920’s and 2.04 million in 2017, indicating that farm sizes are increasing as less farmers tend the land. Capitalism and the widespread vacancies in agricultural jobs have resulted in the “deskilling” of the rural workforce as automated machinery copes with larger farm sizes and lack of available labor (Carlisle et al., 2019, Braverman 1974, USDA ERS 2018). In developed nations, the focus of agriculture has thus centered itself around two goals; maximization of production and the maximization of profits, to the detriment agricultural and neighboring ecosystems and communities (Coleman, 1989; Gliessman & Engles, 2014; Paul & Robertson, 1989). Modern agriculture in the developed world (industrial agriculture) can now be identified by the seven basic practices defined by Gliessman and Engles; tillage, monocultures, irrigation, inorganic fertilizer, chemical pest control, GMO’s, and “factory farming” of animals.

Despite the decrease in the agricultural workforce in developed nations, crop production has consistently increased throughout the 1900’s, notably after the Green Revolution, when production increasing by 56% globally between 1965 and 1985, and 20% between 1985 and 2005 (Foley et al., 2011). With hectares of cultivated land only increasing by 2.4% between 1985 and 2005, this increase in production has been associated with a 25% increase in global crop yields, due to the breeding of new crop varieties, technological progress, chemical inputs, and extensive agricultural infrastructure development (Foley et al., 2011; Gliessman & Engles, 2014). However, despite decreasing the price for food and the exceedance of crop production compared to population growth, the nature of industrialization of agriculture threatens the gains reaped from the process. 

Haber’s 1918 discovery of anthropogenic nitrogen fixation catalyzed a century of booming agricultural production and development, swelling the world population and consumption of nitrogen fertilizer. Between 1940 and 1980, the amount of fertilizer consumed in the United States increased from 9 to 47 million tons and reached 12 Tg N yr-1 in 2015, furthering long held concerns about the ecological and environmental implications of intensive fertilizer use (Gliessman & Engles, 2014; Vitousek et al., 1997). Overapplication of inorganic fertilizers in the quest for maximizing current productivity degrade soils and waters through acidification and eutrophication, contribute to biodiversity loss, GHG emissions, and threaten further productivity on the land and water that agriculture requires (Allaire, Wu, & Lall, 2018; Capel, McCarthy, & Barbash, 2008; DeLonge, Miles, & Carlisle, 2016; Weiner, 2017). Excess nitrogen from fertilizers have been linked to elevated nitrate levels in drinking water and acidification of agricultural soils (Engel, 2012; John et al., 2017; Sigler et al., 2018). The EPA reported that agricultural practices such as crop production, rangelands, and feedlots, are the contaminating source for 70% of the miles of impaired river in the United States, as well as the hypoxic zone in the Gulf of Mexico (USEPA 2000, Osterman et al. 2006). Increased nutrient application that leads to elevated nitrate concentrations in waterways has serious negative potential impacts. Humans who drink nitrate contaminated water are at an acute risk of cancers, birth defects, and other reproductive disorders (Wongsanit et al. 2015, Camargo & Alonso 2006). These detriments cast future productivity into doubt and contribute to increased risk and decreased ecological and economic resilience, as well as global inequality (Carlisle et al., 2019; Gliessman & Engles, 2014).

Since the advent of agriculture, human culture and lifestyle have been influenced by agricultural innovations and technologies (Gross, 2013). Increased productivity in crop yields from the Green Revolution spurred population growth and urbanization that has attracted people from rural demographics to cities, decreasing the population working in agriculture, and driving automation and industrialization of agriculture in developed nations like the United States. Agriculture is stuck in a paradox of increasing food production for a growing population while becoming more efficient and sustainable. The high demands of chemical inputs in industrial agriculture degrade our soils and pollute the air and water, threatening the resource pool upon which future crops rely. While productivity has increased from the Green Revolution, the rate of yield increases has slowed since 1985 and yet, with a projected increase in crop demand of 100-110% from 2005 to 2050, agriculture will need to increase productivity yet again (Foley et al., 2011; Tilman, Balzer, Hill, & Befort, 2011).

While there are a large variety of solutions being pursued for addressing the sustainability crisis in agriculture, changes in land use and management, closing yield gaps, and shifting diets (Bardgett & Gibson, 2017; Foley et al., 2011) , we have known for decades that intensifying production in a sustainable manner on a global scale is undeniably crucial to feeding our growing population. Elliot and Cole call for the shift of agricultural production from maximization to optimization of profits and sustainability in (1989) and describe their simulation modeling approach that used field studies and GIS to make their long-term predictions about the future of agriculture in the United States. Most farm machinery today collects, or at least interacts, with data in one or many ways, and data is a rich resource being generated on and for farms every day (Meola 2016). We are no longer are restricted to long term and large-scale modeling as in the late 1980’s, and because we have field specific data, technology and data collection can be used to inform small-scale management within fields by reducing generalizations made across spatial scales (Lawrence, Rew, & Maxwell, 2015; Maxwell & Luschei, 2005; Gebbers & Adamchuk 2010; Luschei et al. 2001). As resource efficiency remains limited in areas with high technology adoption, greater adoption of the data returned from day to day farming operations can be exploited to drastically increase resource efficiency and produce crops in a manner that reduces the environmental impacts and increase the ecological and economic resilience of agroecosystems (Bucci, Bentivoglio, & Finco, 2018). 

Big data and agriculture have been used together more and more frequently in the past decade, as the amount of information available off farms from machines, drones, weather stations, sensors, etc. and from satellite based remote sensing data, such as weather, topography, vegetation indices, etc. increases on a daily basis (Carolan, 2017). Precision agriculture was developed to harness this technology to farm “smarter” yet is a broad term that covers simply using GPS and satellite guidance, to targeted application of inputs such as fertilizers and pesticides. In the past couple decades, precision agriculture technologies have become commonplace across modern farms in the United States and the globe, with a market for precision agriculture equal to 2.5 billion dollars in 2014 (Carolan, 2017; Michalopoulos 2015). Yet, although vast amounts of data are and have been acquired on-farms and for farms for multiple decades, agriculture have traditionally left this data unused in the development of management decisions, with precision agriculture focusing on GPS and GIS technologies. However, nitrogen fertilizers have been traditionally applied as a uniform rate across fields, and the advent of precision agriculture has spurred experimentation and development of site-specific nitrogen fertilizer applications with the expectation that nitrogen application would be reduced, and crop productivity would be maximized (McBratney, Whelan, Ancev, & Bouma, 2005). Reducing agricultural inputs like fertilizers and pesticides will increase uncertainty in management outcomes, thus, there is a significant opportunity to employ modern data science in agriculture, one of the most data rich arenas in the world, to help understand and manage these systems (Sykuta, 2016).

Embracing technology and the utilization of data in agricultural management makes adaptive management more possible than ever. The automatic collection of data from machines simply requires the extraction by the producer, becoming increasingly easy through cloud software such as “MyJohnDeere” (product citation). The data available includes as-applied maps of inputs such as seeds, fertilizers, pesticides and production and quality (e.g. crop yield and grain protein content). The additional prevalence of remotely sensed satellite data provides a trove of data available to understand and amend management specific to fields. Remotely sensed productivity data can be collected at 2-4-week intervals from open source imagery or as often as desired with private drone flights. Weather stations are also becoming increasingly common on farms, providing spatially accurate and temporally dense measurements of variables such as precipitation and temperature. The combination of these temporally dense measurements provides information for adaptive management at a finer scale than ever. This enables rapid response to weeds, insects, disease, tailored fertilizer and seeding rates, and resiliency planning. 

Assessments of agricultural sustainability must consider the economic, environmental, and social health of agricultural systems (Foley et al., 2011). Advancement of sustainable agriculture requires three progressive steps: (1) increasing efficiency, (2) substituting inputs, and (3) redesigning the cropping system (Miller 2018). Corollary to this is the benefit of protecting soil and water resources that influence system health (Foley et al., 2011). Precision agriculture is a middle ground between conventional systems and organic systems, in which efficiency of inputs is targeted, and therefore constitutes a first step towards sustainability. Contemporary precision agriculture uses technology and data collection to inform small-scale management across fields to increase efficiency of inputs on farms by reducing spatial averaging of input application rates (Gebbers and Adamchuck 2010). By studying the consequences of targeted input application, key insights can be gained about N regulation within the farming system.

Site-specific N management is an application of precision agriculture that can address the issues surrounding excess fertilizer rates by reducing the waste of nutrients in areas where no nutrient additions are needed. By managing on a site-specific basis, within-field spatial variability in crop responses can be evaluated and utilized to maximize net returns for producers by saving money on the amount of nitrogen needed for crop production while minimizing the amount of nitrogen that has the potential to be lost to the surrounding ecosystem. 

Site-specific nitrogen management varies greatly in the methods used to develop prescriptions and the scale at which management units are applied (Link et al. 2008, Huggins 2010, Farid et al. 2015, Khosla et al. 2008, Koch et al. 2004, Moshia et al. 2014). Site-specific fertilizer applications have been investigated in corn and wheat systems throughout the US (Bronson et al. 2006, Guillard 2018, Stevens 2017, Flowers et al. 2004, Biermacher et al. 2009); however, no projects have analyzed site-specific nitrogen management as a potential for reducing nitrate pollution in the dryland wheat systems of the Northern Great Plains. Soil acidification is being studied in dryland production systems in Montana to develop remediation and management alternatives to excessive nitrogen applications (Engel, 2012). However, site-specific nitrogen applications are not currently being investigated to provide solutions. 

Site-specific nitrogen management can address the issues surrounding excess fertilizer application by reducing fertilizer rates in areas where the crop response does not result in increased net returns. Understanding the relationship between crop yields and protein and N loss and NUE with N fertilizer could result in more informed decisions on fertilizer management to optimize yield and protein content of wheat in dryland settings on maximizing net-returns and preventing the over application of N to preserve natural resources that farmers rely on. Quantifying environmental and economic consequences between management optimization on net return and nitrate loss reduction relates to both of the aforementioned priorities as this will contribute to economic improvement for farmers as well as sustainment of natural resources. The combination of these two factors will irrefutably improve rural communities by increasing producer incomes that drive rural economies as well as enhancing rural quality of life by protecting the environment that they enjoy and utilize to create and sustain jobs. The positive implications of site-specific nitrogen application are large and understanding the process of nitrate pollution and development of economically optimizing fertilizer management tools will aid in the global satisfaction of food and fiber needs, sustain environmental quality of natural resources, efficiently use resources, sustain the economic viability of farms, and improve quality of life for farmers and society as a whole. 

There are two major implications associated with site-specific nitrogen management. Divesting more resources from low profit potential areas than the investment of resources into high profit potential areas results in reduction of nitrogen applied over a field and resulted in less expenditures by producers for fertilizer (Khosla et al. 2008, Koch et al. 2004). Profit maximizing site-specific nitrogen management has been shown to increase net returns from Oklahoma to Montana (Biermacher et al. 2009; Lawrence, Rew, & Maxwell, 2015). However, site-specific management should be evaluated for efficacy on a field by field basis, as spatial variability results in fields where site-specific nitrogen management nets the greatest economic returns, and fields where other drivers besides nitrogen impact net returns (Koch et al. 2004, Link et al. 2008). The potential for site-specific nitrogen management to reduce the amount of nitrogen applied to agricultural fields not only decreases the amount spent by a grower on fertilizer, but addresses environmental concerns related to excess application of nitrogen (Auernhammer 2001). There is evidence that site-specific nitrogen management can potentially decreases application rates of nitrogen fertilizer across corn and wheat systems (Flowers et al. 2004, Khosla et al. 2002, Koch et al. 2004). Link et al. (2008) highlight that site-specific management is appropriate on a field-specific basis and that, even within similar cropping systems and geographies, responses often vary.

Site-specific N fertilizer management provides the data framework that producers can use for adapting a management approach to the “many little hammers” used in integrated weed management (Liebman & Gallandt, 1997). Prescribing N rates on a site-specific basis is one of the tiny hammers of agroecology and sustainable agriculture. However, collected such fine resolution data can inform the development and application of other tiny hammers. The spatiotemporal availability of remotely sensed data allows for enrichment of any dataset, but the collection of crop response data from machines on the farm can inform the management of other inputs. For example, remotely sensed weather estimates can be used to adapt irrigation management on a manager specified timescale, crop responses to seed rates can be investigated, and the influence of non-chemical inputs can be assessed through experimentation and regression analysis. 

Montana farmer’s economic resilience depends on maximized input use efficiency, yet the complex decisions on managing for efficiency are subject to significant uncertainty. Variability in the cost of inputs, crop prices, and spatiotemporal crop responses to the environment and climate drive the economic uncertainty of Montana producers. Application of N fertilizer to winter wheat in the spring is expected to increase grain yield and protein, yet, producers observe inconsistencies in crop responses to fertilizer within and across years for each field. Bruce Maxwell’s On-Farm Precision Experiment (OFPE) framework (website citation) is based on the belief that management recommendations that minimize economically, and environmentally costly inputs require field specific knowledge of input performance. The OFPE project harnesses precision agriculture technologies like GPS guided variable rate application (VRA) and on-the-go yield and protein monitoring data with the enormous stream of data from the internet to develop crop response functions to inputs for each field. Gathering field specific knowledge is accelerated by strategically laying out experiments in each field using artificial intelligence (AI) to understand the drivers of spatial variability in crop response. Each year’s field specific experimental results are stored to build knowledge on the temporal variability required to make predictive management decisions. Because the focus is on using data produced on the field to manage that field, no universal prescriptions or knowledge are of interest. The OFPE project is developing a fully automated mechanism (software) to conduct in-field experimentation with current technologies that will improve the profitability of nitrogen fertilizer management decisions in Montana wheat production. This software will serve as a decision aid for farmers that utilizes data collected on-farms from routine operations, as well as remote sensing data from open source repositories, to optimize site-specific inputs, such as nitrogen fertilizer, based on maximized net returns and resource use efficiency in Montana small grain dryland agroecosystems (Payn et al. n.d.). This is a participatory research project, crucial to advancing agricultural innovation (Bonny et al., 2005), involving farmer collaborators and applying experiments and knowledge directly to their fields. The belief is that farm managers can take advantage of the “big data” flowing into and from modern agriculture technologies and advanced analytics to make input management more profitable. While striking a similar chord as the industry applications of precision agriculture, four principles distinguish the OFPE from the industry approach; 1) Experiments are intended to inform management on the field where conducted, not other fields, 2) All variables used to predict yield and protein are from previous years or up to decision point in time. Only uses information that would be available to the producer at the time of a decision as well as only information that is gathered from farmer operations or open sources, 3) Once prediction equations are built for a field, the manager can simulate different net return outcomes given different weather and price conditions that most closely match the current year when decision is made, or explore a possible range of outcomes, 4) After predicted conditions are identified, the manager can compare the possible management approaches and determine the probability (if any) that site-specific management will produce the highest return on investment. OFPE consists of optimizing inputs to maximize profits and to eventually maximize resource use efficiency in a quantifiable way. This optimization attempts to remove the aspect of uncertainty by experimentally determining input performance on each field, addressing spatial variability and repeating the experiments to understand temporal variability in crop response.

The data available from farms, and more specifically, from fields allows for land managers to manage their fields on a field specific basis. This reduces information degradation when management strategies developed at research stations many miles away are used to inform management on specific fields (Maxwell & Luschei, 2005). To improve our decisions in a more sustainable fashion, more thought on the ecology of the system’s managed is required. Unfortunately, the site, time, and history specificity of fields has complicated integration of ecological principles into agriculture, which relies on regionwide prescriptions.

We expect that crop responses not only vary across a field in a single year, but they vary across years. Additionally, while the response of crops in fields hundreds of miles apart is undoubtedly different, crop responses of fields of the same farm vary. The underutilized data available from farms not only helps identify this variation but can be used to understand and optimize on these differences. Data driven agriculture informs more than just the spatial management of inputs but can also inform whether application of inputs is required. The characterization of the relationship of crop productivity or quality to N fertilizer by harnessing the data available from fields and experimentally varying fertilizer rates, allows us to identify when fertilizer additions do not contribute to positive crop responses. This information enables the manager to assess the risks and rewards of not applying any fertilizer during a given year. However, the majority of farmer decisions are not data driven and are applied generally across all of their fields. 

Harvest machine crop yield and protein monitoring technology and data collected from internet sources (e.g. Google Earth Engine) were used to inform site-specific within field fertilizer management (Lawrence et al. 2015) for this study. This study harnesses the data revolution in agriculture to ask how the ability of gathering field specific data influences management decisions? We ask what are the drivers of production, quality, and net-returns within and between fields for a given year and how do these change between years?




